import { useCallback, useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { CalendarDays, ClipboardPlus, Plus, UserRound } from 'lucide-react'
import { formatDate } from '../../../shared/dates.ts'
import { formatAmount } from '../../../shared/money.ts'
import type { ActivitySummary, ProjectSummary, TaskSummary, UserSummary } from '../../../shared/types.ts'
import { Alert, Badge, Button, Card, EmptyState, Field, Input, Modal, PageHeader, Select, Textarea } from '../../components/ui'
import { ApiError, createActivityApi, createTaskApi, fetchActivities, fetchProjects, fetchTasks, fetchUsers } from '../../lib/api'

export const TasksPage = () => {
  const [tasks, setTasks] = useState<TaskSummary[]>([]); const [activities, setActivities] = useState<ActivitySummary[]>([]); const [projects, setProjects] = useState<ProjectSummary[]>([]); const [users, setUsers] = useState<UserSummary[]>([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [feedback, setFeedback] = useState(''); const [taskOpen, setTaskOpen] = useState(false); const [activityOpen, setActivityOpen] = useState(false)
  const taskForm = useForm(); const activityForm = useForm()
  const load = useCallback(async () => { try { const [a, b, c, d] = await Promise.all([fetchTasks(), fetchActivities(), fetchProjects(), fetchUsers()]); setTasks(a.tasks); setActivities(b.activities); setProjects(c.projects); setUsers(d.users.filter((user) => user.isActive && user.role !== 'CLIENT')); setError('') } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Chargement des tâches impossible.') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const createActivity = async (data: Record<string, unknown>) => { try { await createActivityApi(data as { projectId: string; name: string; description?: string }); setActivityOpen(false); setFeedback('Activité créée. Vous pouvez maintenant y distribuer des tâches.'); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Création de l’activité impossible.') } }
  const createTask = async (data: Record<string, unknown>) => { try { await createTaskApi(data as { activityId: string; assignedUserId: string; name: string; clientPriceShare?: number }); setTaskOpen(false); setFeedback('Tâche distribuée. Sa date est calculée automatiquement à J‑5.'); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Distribution impossible.') } }
  const openTask = () => { taskForm.reset({ activityId: activities[0]?.id ?? '', assignedUserId: users[0]?.id ?? '', name: '', clientPriceShare: 0 }); setTaskOpen(true) }
  return <div className="space-y-6"><PageHeader title="Tâches" subtitle="Distribuez le travail et suivez les livraisons automatiques à J‑5." actions={<div className="flex gap-2"><Button variant="secondary" onClick={() => { activityForm.reset({ projectId: projects[0]?.id ?? '', name: '', description: '' }); setActivityOpen(true) }} disabled={!projects.length}><Plus className="h-4 w-4" />Activité</Button><Button onClick={openTask} disabled={!activities.length || !users.length}><ClipboardPlus className="h-4 w-4" />Distribuer</Button></div>} />
    {feedback ? <Alert tone="success">{feedback}</Alert> : null}{error ? <Alert tone="error">{error}</Alert> : null}
    {!activities.length && !loading ? <Alert tone="info">Créez une activité liée à un projet, puis attribuez une ou plusieurs tâches à vos membres.</Alert> : null}
    {loading ? <Card className="p-12 text-center text-sm text-studio-dark/55">Chargement des tâches…</Card> : tasks.length === 0 ? <EmptyState icon={<ClipboardPlus className="h-6 w-6" />} title="Aucune tâche distribuée" description="Une activité peut recevoir plusieurs tâches, chacune attribuée à un membre." action={<Button onClick={openTask} disabled={!activities.length || !users.length}>Distribuer une tâche</Button>} /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tasks.map((task) => <Card key={task.id} className="space-y-3"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-studio-terracotta">{task.projectName} · {task.activityName}</p><h2 className="mt-1 font-serif text-lg font-bold">{task.name}</h2></div><Badge tone={task.status === 'COMPLETED' ? 'green' : task.status === 'IN_REVIEW' ? 'gold' : 'gray'}>{task.status === 'PENDING' ? 'À faire' : task.status === 'IN_REVIEW' ? 'À vérifier' : 'Terminée'}</Badge></div><p className="flex items-center gap-2 text-sm"><UserRound className="h-4 w-4 text-studio-terracotta" />{task.assignedUserName}</p><p className="flex items-center gap-2 text-sm"><CalendarDays className="h-4 w-4 text-studio-terracotta" />À livrer le {formatDate(task.deliveryDate)}</p><div className="grid grid-cols-2 border-t border-studio-dark/10 pt-3 text-xs"><div><p className="text-studio-dark/45">Part client</p><strong>{formatAmount(task.clientPriceShare ?? 0)}</strong></div><div><p className="text-studio-dark/45">Rémunération membre</p><strong className="text-green-700">{formatAmount(task.memberPayout ?? 0)}</strong></div></div></Card>)}</div>}
    <Modal open={activityOpen} onClose={() => setActivityOpen(false)} size="lg" title="Nouvelle activité" subtitle="Une activité regroupe les tâches d’un projet."><form className="space-y-4" onSubmit={activityForm.handleSubmit(createActivity)}><Field label="Projet *"><Select {...activityForm.register('projectId')}><option value="">Sélectionnez un projet</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.eventName} — {p.clientName}</option>)}</Select></Field><Field label="Nom de l’activité *"><Input {...activityForm.register('name', { required: true })} placeholder="Ex. Shooting Jour J" /></Field><Field label="Description"><Textarea {...activityForm.register('description')} /></Field><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setActivityOpen(false)}>Annuler</Button><Button type="submit">Créer l’activité</Button></div></form></Modal>
    <Modal open={taskOpen} onClose={() => setTaskOpen(false)} size="lg" title="Distribuer une tâche" subtitle="La date de livraison est automatiquement calculée à J‑5 de la livraison globale du projet."><form className="space-y-4" onSubmit={taskForm.handleSubmit(createTask)}><Field label="Activité *"><Select {...taskForm.register('activityId')}><option value="">Sélectionnez une activité</option>{activities.map((a) => <option key={a.id} value={a.id}>{a.projectName} — {a.name}</option>)}</Select></Field><Field label="Membre *"><Select {...taskForm.register('assignedUserId')}><option value="">Sélectionnez un membre</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</Select></Field><Field label="Nom de la tâche *"><Input {...taskForm.register('name', { required: true })} placeholder="Ex. Retouche de la galerie" /></Field><Field label="Montant client (admin)"><Input {...taskForm.register('clientPriceShare', { valueAsNumber: true })} type="number" min="0" /></Field><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setTaskOpen(false)}>Annuler</Button><Button type="submit">Distribuer</Button></div></form></Modal>
  </div>
}
