import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, CalendarDays, CheckCircle2, ExternalLink, Wallet } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { formatDate } from '../../../shared/dates.ts'
import { formatAmount } from '../../../shared/money.ts'
import type { TaskSummary } from '../../../shared/types.ts'
import { Alert, Badge, Button, Card, Field, Input, PageHeader, Select, StatCard } from '../../components/ui'
import { useAuth } from '../../context/AuthContext'
import { ApiError, fetchTask, payTaskPayoutApi, updateOwnTaskApi } from '../../lib/api'

const labels: Record<TaskSummary['status'], string> = { PENDING: 'À faire', IN_REVIEW: 'En cours', COMPLETED: 'Terminée' }
const tones: Record<TaskSummary['status'], 'gray' | 'gold' | 'green'> = { PENDING: 'gray', IN_REVIEW: 'gold', COMPLETED: 'green' }

export const TaskDetailPage = () => {
  const { id } = useParams<{ id: string }>(); const { user, isAdmin } = useAuth()
  const [task, setTask] = useState<TaskSummary | null>(null); const [error, setError] = useState(''); const [feedback, setFeedback] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { if (!id) return; try { setTask((await fetchTask(id)).task); setError('') } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Chargement de la tâche impossible.') } finally { setLoading(false) } }, [id])
  useEffect(() => { void load() }, [load])
  const saveProgress = async (form: FormData) => { if (!task) return; const status = String(form.get('status')) as TaskSummary['status']; const proofLink = String(form.get('proofLink') ?? '').trim(); if (status === 'COMPLETED' && !proofLink) { setError('Ajoutez le lien de la photo ou de la vidéo avant de terminer la tâche.'); return } setSaving(true); try { await updateOwnTaskApi(task.id, { status, proofLink }); setFeedback('Avancement mis à jour.'); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Mise à jour impossible.') } finally { setSaving(false) } }
  const pay = async () => { if (!task || !window.confirm(`Confirmer le paiement de ${formatAmount(task.memberPayout ?? 0)} ?`)) return; setSaving(true); try { await payTaskPayoutApi(task.id); setFeedback('Rémunération marquée comme payée et ajoutée aux finances.'); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Paiement impossible.') } finally { setSaving(false) } }
  if (loading) return <Card className="p-12 text-center text-sm text-studio-dark/55">Chargement de la tâche…</Card>
  if (!task) return <div className="space-y-4"><Alert tone="error">{error || 'Tâche introuvable.'}</Alert><Link to="/mes-taches"><Button variant="secondary"><ArrowLeft className="h-4 w-4" />Retour</Button></Link></div>
  const isAssignee = user?.id === task.assignedUserId
  return <div className="space-y-6"><Link to={isAdmin ? `/activites/${task.activityId}` : '/mes-taches'} className="inline-flex items-center gap-1 text-sm text-studio-terracotta hover:underline"><ArrowLeft className="h-4 w-4" />Retour aux tâches</Link><PageHeader title={task.name} subtitle={`${task.projectName} · ${task.activityName}`} actions={<Badge tone={tones[task.status]}>{labels[task.status]}</Badge>} />{error ? <Alert tone="error">{error}</Alert> : null}{feedback ? <Alert tone="success">{feedback}</Alert> : null}<div className="grid gap-4 md:grid-cols-3"><StatCard label="Statut" value={labels[task.status]} /><StatCard label="À livrer le" value={formatDate(task.deliveryDate)} icon={<CalendarDays className="h-5 w-5" />} /><StatCard label="Responsable" value={task.assignedUserName} /></div><Card className="space-y-3"><h2 className="font-serif text-xl font-bold">Informations de la tâche</h2><p><strong>Projet :</strong> {task.projectName}</p><p><strong>Activité :</strong> {task.activityName}</p>{task.proofLink ? <p><strong>Preuve :</strong> <a className="inline-flex items-center gap-1 text-studio-terracotta underline" href={task.proofLink} target="_blank" rel="noreferrer">Ouvrir la photo ou vidéo <ExternalLink className="h-3.5 w-3.5" /></a></p> : <p className="text-studio-dark/55">Aucune preuve envoyée pour le moment.</p>}</Card><Card className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-serif text-xl font-bold">Ma rémunération</h2><p className="mt-1 text-sm text-studio-dark/60">Montant prévu : {formatAmount(task.memberPayout ?? 0)}</p><p className={task.payoutPaidAt ? 'mt-1 text-sm font-semibold text-green-700' : 'mt-1 text-sm font-semibold text-studio-terracotta'}>{task.payoutPaidAt ? `Payée le ${formatDate(task.payoutPaidAt)}` : 'En attente de paiement'}</p></div>{isAdmin ? (!task.payoutPaidAt ? <Button onClick={() => void pay()} disabled={task.status !== 'COMPLETED' || !task.memberPayout} loading={saving}><Wallet className="h-4 w-4" />Marquer comme payée</Button> : <Badge tone="green">Payée</Badge>) : null}</Card>{isAssignee && !isAdmin ? <Card><h2 className="font-serif text-xl font-bold">Mettre à jour mon travail</h2><form className="mt-4 space-y-4" action={(form) => void saveProgress(form)}><Field label="Statut"><Select name="status" defaultValue={task.status}><option value="PENDING">À faire</option><option value="IN_REVIEW">En cours</option><option value="COMPLETED">Terminée</option></Select></Field><Field label="Preuve - lien vers une photo ou vidéo"><Input name="proofLink" type="url" defaultValue={task.proofLink ?? ''} placeholder="https://drive.google.com/..." /></Field><p className="text-xs text-studio-dark/55">Ajoute le lien de partage de ta photo ou vidéo. Cette preuve devient obligatoire quand tu choisis « Terminée ».</p><Button type="submit" loading={saving}><CheckCircle2 className="h-4 w-4" />Enregistrer l’avancement</Button></form></Card> : null}</div>
}
