import { useEffect, useState } from 'react'
import { Button, Card, Field, Input, PageHeader, Skeleton, useToast } from '../../components/ui'
import { ApiError, fetchSettings, updateSettingsApi } from '../../lib/api'

export const SettingsPage = () => {
  const toast = useToast()
  const [settings, setSettings] = useState<Record<string, unknown> | null>(null); const [saving, setSaving] = useState(false)
  useEffect(() => { fetchSettings().then(({ settings: data }) => setSettings(data)).catch((e: unknown) => toast.error(e instanceof ApiError ? e.message : 'Chargement impossible.')) }, [toast])
  const save = async (form: FormData) => { setSaving(true); try { const payload = Object.fromEntries(form); await updateSettingsApi(payload); toast.success('Réglages enregistrés.') } catch (e) { toast.error(e instanceof ApiError ? e.message : 'Enregistrement impossible.') } finally { setSaving(false) } }
  if (!settings) return <div className="space-y-6"><Card className="space-y-3"><Skeleton className="h-5 w-40" /><Skeleton className="h-10 w-full" /><Skeleton className="h-10 w-full" /><Skeleton className="h-10 w-2/3" /></Card><Card className="space-y-3"><Skeleton className="h-5 w-40" /><Skeleton className="h-10 w-full" /><Skeleton className="h-10 w-full" /></Card></div>
  const value = (key: string) => String(settings[key] ?? '')
  return <div className="space-y-6"><PageHeader title="Réglages du studio" subtitle="Informations utilisées pour les reçus et valeurs par défaut des nouveaux projets." /><form className="space-y-6" action={(form) => void save(form)}><Card className="space-y-4"><h2 className="font-serif text-xl font-bold">Identité du studio</h2><Field label="Nom"><Input name="name" defaultValue={value('name')} required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Téléphone"><Input name="phone" defaultValue={value('phone')} /></Field><Field label="Email"><Input name="email" type="email" defaultValue={value('email')} /></Field></div><Field label="Adresse"><Input name="address" defaultValue={value('address')} /></Field><Field label="NIU / RCCM"><Input name="registrationNumber" defaultValue={value('registrationNumber')} /></Field></Card><Card className="space-y-4"><h2 className="font-serif text-xl font-bold">Valeurs par défaut</h2><div className="grid gap-4 sm:grid-cols-3"><Field label="Avance %"><Input name="defaultPercentAdvance" type="number" defaultValue={value('defaultPercentAdvance')} required /></Field><Field label="Intermédiaire %"><Input name="defaultPercentIntermediate" type="number" defaultValue={value('defaultPercentIntermediate')} required /></Field><Field label="Solde %"><Input name="defaultPercentFinal" type="number" defaultValue={value('defaultPercentFinal')} required /></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Délai tâches (jours)"><Input name="taskDeliveryLeadDays" type="number" defaultValue={value('taskDeliveryLeadDays')} required /></Field><Field label="Devise"><Input name="currency" defaultValue={value('currency')} required /></Field><Field label="Préfixe reçus"><Input name="receiptPrefix" defaultValue={value('receiptPrefix')} required /></Field></div></Card><div className="flex justify-end"><Button type="submit" loading={saving}>Enregistrer les réglages</Button></div></form></div>
}
